### ISSUE TITLE
Create SiteInfo Class

### ISSUE THREAD

**Issue by davefeucht** [davefeucht/photo-portfolio-backend#9]
```
{
        description: string,
        gmt_offset: string,
        home: string,
        name: string,
        site_icon: number,
        site_icon_url: string,
        site_logo: number,
        timezone_string: string,
        url: string
}
```

description: text description of site
gmt_offset: gmt offset where site is located
name: text name of the site
site_icon: ID of a media entry which is used as the site icon
site_logo: ID of a media entry which is used as the site logo
url: base url of the site

`home`, `site_icon_url` and `timezone_string` can be removed.

**Comment by eoikonomou** [comment]
Can you add more information on the fields? I do not fully understand why the `site_icon` and `site_logo` are numbers. Are they the ids of the assets for the site icon and the site logo? Also, what about the timezone_string? Is this a date or the locale?
